### ISSUE TITLE
Petits bugs

### ISSUE THREAD

**Issue by Demoniakillah** [alk13/bomifier#1]
Salut,
j'ai détecté quelques bug dans la classe Bomifier,
- le constructeur est en protected (l.20)
- il manque l'antislash devant Exception (l.110)
- il manque le 'f' à la fonction sprintf (l.110)

voilà ;) bon courage

sinon super librairie très utile merci

**Comment by beeraw** [comment]
Merci. Je corrige ça dans la journée.

**Comment by Demoniakillah** [comment]
Dans le constructeur, tu propose d'instancier la class sans paramètre, mais dans ton setUri(), une exception est levée. 

je te propose de remplacer ta condition par celle-ci :

```
if (!empty($uri) && !is_file($uri)) {
            throw new \Exception(sprintf('File %s not found.', $uri));
        }
```

ps: Fahari te passe le bonjour

**Comment by beeraw** [comment]
Je devais être bourré quand je vois les conneries que j'ai faites...

P.S. : Passe lui le bonjour également.

**Comment by Demoniakillah** [comment]
loooool on est tous passé par là.

Super pratique en tout cas, tu me sors d'une galère

Merci
